// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PaymentColumns holds the columns for the "Payment" table.
	PaymentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "date_created", Type: field.TypeTime},
		{Name: "date_updated", Type: field.TypeTime},
	}
	// PaymentTable holds the schema information for the "Payment" table.
	PaymentTable = &schema.Table{
		Name:       "Payment",
		Columns:    PaymentColumns,
		PrimaryKey: []*schema.Column{PaymentColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PaymentTable,
	}
)

func init() {
	PaymentTable.Annotation = &entsql.Annotation{
		Table: "Payment",
	}
}
