// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chipin/ent/payment"
	"chipin/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	paymentMixin := schema.Payment{}.Mixin()
	paymentMixinFields0 := paymentMixin[0].Fields()
	_ = paymentMixinFields0
	paymentMixinFields1 := paymentMixin[1].Fields()
	_ = paymentMixinFields1
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescDateCreated is the schema descriptor for date_created field.
	paymentDescDateCreated := paymentMixinFields0[0].Descriptor()
	// payment.DefaultDateCreated holds the default value on creation for the date_created field.
	payment.DefaultDateCreated = paymentDescDateCreated.Default.(func() time.Time)
	// paymentDescDateUpdated is the schema descriptor for date_updated field.
	paymentDescDateUpdated := paymentMixinFields0[1].Descriptor()
	// payment.DefaultDateUpdated holds the default value on creation for the date_updated field.
	payment.DefaultDateUpdated = paymentDescDateUpdated.Default.(func() time.Time)
	// payment.UpdateDefaultDateUpdated holds the default value on update for the date_updated field.
	payment.UpdateDefaultDateUpdated = paymentDescDateUpdated.UpdateDefault.(func() time.Time)
	// paymentDescID is the schema descriptor for id field.
	paymentDescID := paymentMixinFields1[0].Descriptor()
	// payment.DefaultID holds the default value on creation for the id field.
	payment.DefaultID = paymentDescID.Default.(func() uuid.UUID)
}
