package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"chipin/resolvers/generated"
	"context"
	"fmt"
)

// Checkout is the resolver for the Checkout field.
func (r *mutationResolver) Checkout(ctx context.Context, cartID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Checkout - Checkout"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
